In [1]:
import pandas as pd
import numpy as np

Thanks to Kriti Mahajan. This table was developed with study type features extracted from the meta data.
Code found here: https://colab.research.google.com/drive/1lay-yWJ5ohN94lQLHYIxtWMuDWtCRGy0#scrollTo=N-IhAeEkcxDe

Strategy:
1. For each data source, normalize columns to newest CoY label set (one Dan QC'd).
2. Eventually Drop Other column since not defined the same across datasets.
2. Combine v9 CoY dataset, Kaggle dataset, PubMed datasets all into one Study Type annotation table.

### Trying direct merge with mf and kaggle label set via sha.

In [151]:
mf = pd.read_csv('metadata_features-2.csv')
mf

Unnamed: 0  paper_id  \
0               0  zjufx4fo   
1               1  ymceytj3   
2               2  wzj2glte   
3               3  2sfqsfm1   
4               4  i0zym7iq   
...           ...       ...   
59125       59125  pwq5gir9   
59126       59126  3racv2qe   
59127       59127  jngto9kv   
59128       59128  td0776wj   
59129       59129  jxbr6hbk   

                                                     sha  \
0               b2897e1277f56641193a6db73825f707eed3e4c9   
1               e3d0d482ebd9a8ba81c254cc433f314142e72174   
2               00b1d99e70f779eb4ede50059db469c65e8c1469   
3               cf584e00f637cbd8f1bb35f3f09f5ed07b71aeb0   
4               dde02f11923815e6a16a31dd6298c46b109c5dfa   
...                                                  ...   
59125           20f185b11fa23da8938efb5c839c6c078c66f1e9   
59126           e84532333db8f219f20ae0a8fe18130c0d010b04   
59127           31105078a2953217223699d09c6a80d0f5edfdf6   
59128           b1f977d58a0eba25acdee5912ef71c372b0632de   
59129  4eb170db0dd666fc669649d0e6b15e513b6598d6; 9403...   

                                                   title  \
0      Sequence requirements for RNA strand transfer ...   
1      Crystal structure of murine sCEACAM1a[1,4]: a ...   
2      Synthesis of a novel hepatitis C virus protein...   
3      Structure of coronavirus main proteinase revea...   
4      Discontinuous and non-discontinuous subgenomic...   
...                                                  ...   
59125  Cutting-Edge Infectious Disease Diagnostics wi...   
59126  Intranasal administration of oxytocin: Behavio...   
59127  Infecciones virales graves en pacientes inmuno...   
59128  18 Omics, Bioinformatics, and Infectious Disea...   
59129  Identifying spatio-temporal dynamics of Ebola ...   

                                                abstract publish_time  \
0      Nidovirus subgenomic mRNAs contain a leader se...   2001-12-17   
1      CEACAM1 is a member of the carcinoembryonic an...   2002-05-01   
2      Hepatitis C virus (HCV) is an important human ...   2001-07-16   
3      The key enzyme in coronavirus polyprotein proc...   2002-07-01   
4      Arteri-, corona-, toro- and roniviruses are ev...   2002-12-01   
...                                                  ...          ...   
59125  Three recent Science articles (Chen et al., 20...   2018-06-13   
59126  Abstract The intranasal (IN-) administration o...   2013-09-30   
59127  Resumen Los virus tienen un papel importante d...   2011-04-30   
59128  Bioinformatics and the ‘omics’ studies are rap...   2011-12-31   
59129  Containing the recent West African outbreak of...   2017-11-29   

                                                 authors  \
0      Pasternak, Alexander O.; van den Born, Erwin; ...   
1      Tan, Kemin; Zelus, Bruce D.; Meijers, Rob; Liu...   
2      Xu, Zhenming; Choi, Jinah; Yen, T.S.Benedict; ...   
3      Anand, Kanchan; Palm, Gottfried J.; Mesters, J...   
4      van Vliet, A.L.W.; Smits, S.L.; Rottier, P.J.M...   
...                                                  ...   
59125                                      Chiu, Charles   
59126                   Veening, Jan G.; Olivier, Berend   
59127  Díaz, A.; Zaragoza, R.; Granada, R.; Salavert, M.   
59128       Paszkiewicz, Konrad H.; Giezen, Mark van der   
59129             Gustafson, Kyle B.; Proctor, Joshua L.   

                                                     url  \
0      http://europepmc.org/articles/pmc125340?pdf=re...   
1      http://europepmc.org/articles/pmc125375?pdf=re...   
2      https://www.ncbi.nlm.nih.gov/pmc/articles/PMC1...   
3      http://europepmc.org/articles/pmc126080?pdf=re...   
4      http://europepmc.org/articles/pmc136939?pdf=re...   
...                                                  ...   
59125         https://doi.org/10.1016/j.chom.2018.05.016   
59126    https://doi.org/10.1016/j.neubiorev.2013.04.012   
59127        https://doi.org/10.1016/j.medin.2011.01.0

In [152]:
list(mf)

['Unnamed: 0',
 'paper_id',
 'sha',
 'title',
 'abstract',
 'publish_time',
 'authors',
 'url',
 'Statistical Methods',
 'statistical_method_details',
 'Study Type',
 'study_type_details',
 'results',
 'coronavirus',
 'fatality',
 'sample_size',
 'paper_focus',
 'variables_controlled_for']

In [153]:
features = mf.drop(columns = ['Unnamed: 0',
 'title',
 'abstract',
 'publish_time',
 'authors',
 'url',
 'Statistical Methods',
 'statistical_method_details',
 'study_type_details',
 'results',
 'coronavirus',
 'fatality',
 'sample_size',
 'paper_focus',
 'variables_controlled_for'])
features

paper_id                                                sha  \
0      zjufx4fo           b2897e1277f56641193a6db73825f707eed3e4c9   
1      ymceytj3           e3d0d482ebd9a8ba81c254cc433f314142e72174   
2      wzj2glte           00b1d99e70f779eb4ede50059db469c65e8c1469   
3      2sfqsfm1           cf584e00f637cbd8f1bb35f3f09f5ed07b71aeb0   
4      i0zym7iq           dde02f11923815e6a16a31dd6298c46b109c5dfa   
...         ...                                                ...   
59125  pwq5gir9           20f185b11fa23da8938efb5c839c6c078c66f1e9   
59126  3racv2qe           e84532333db8f219f20ae0a8fe18130c0d010b04   
59127  jngto9kv           31105078a2953217223699d09c6a80d0f5edfdf6   
59128  td0776wj           b1f977d58a0eba25acdee5912ef71c372b0632de   
59129  jxbr6hbk  4eb170db0dd666fc669649d0e6b15e513b6598d6; 9403...   

               Study Type  
0         ['mutagenesis']  
1                      []  
2                      []  
3         ['mutagenesis']  
4                      []  
...                   ...  
59125        ['clinical']  
59126          ['review']  
59127          ['review']  
59128  ['bioinformatics']  
59129         ['genetic']  

[59130 rows x 3 columns]

In [154]:
features['Study Type'].value_counts()

[]                                                                           37266
['clinical']                                                                  5782
['review']                                                                    3594
['genetic']                                                                   3089
['review', 'clinical']                                                        1347
                                                                             ...  
['retrospective study', 'retrospectively analyzed']                              1
['retrospective study', 'histories']                                             1
['review', 'retrospective study', 'retrospectively analyzed', 'clinical']        1
['review', 'single center study', 'clinical']                                    1
['meta-analysis', 'clinical', 'bioinformatics']                                  1
Name: Study Type, Length: 393, dtype: int64

In [155]:
to_drop = ['[]']
features = features[~features['Study Type'].isin(to_drop)]
features

paper_id                                                sha  \
0      zjufx4fo           b2897e1277f56641193a6db73825f707eed3e4c9   
3      2sfqsfm1           cf584e00f637cbd8f1bb35f3f09f5ed07b71aeb0   
6      gi6uaa83           8ae137c8da1607b3a8e4c946c07ca8bda67f88ac   
7      0m32ecnu           23bc55d6f63fab18b02004483888db2b6a0bfa48   
10     fy4w7xz8           0104f6ceccf92ae8567a0102f89cbb976969a774   
...         ...                                                ...   
59125  pwq5gir9           20f185b11fa23da8938efb5c839c6c078c66f1e9   
59126  3racv2qe           e84532333db8f219f20ae0a8fe18130c0d010b04   
59127  jngto9kv           31105078a2953217223699d09c6a80d0f5edfdf6   
59128  td0776wj           b1f977d58a0eba25acdee5912ef71c372b0632de   
59129  jxbr6hbk  4eb170db0dd666fc669649d0e6b15e513b6598d6; 9403...   

                     Study Type  
0               ['mutagenesis']  
3               ['mutagenesis']  
6      ['genetic', 'histories']  
7                   ['genetic']  
10                  ['genetic']  
...                         ...  
59125              ['clinical']  
59126                ['review']  
59127                ['review']  
59128        ['bioinformatics']  
59129               ['genetic']  

[21864 rows x 3 columns]

In [156]:
features['Study Type'].value_counts()

['clinical']                                                        5782
['review']                                                          3594
['genetic']                                                         3089
['review', 'clinical']                                              1347
['experimental']                                                    1241
                                                                    ... 
['review', 'retrospective cohort', 'case series', 'clinical']          1
['review', 'retrospective study', 'clinical', 'laboratory data']       1
['experimental', 'meta-analysis']                                      1
['time series', 'time-series', 'clinical']                             1
['mutagenesis', 'review', 'life cycle']                                1
Name: Study Type, Length: 392, dtype: int64

In [157]:
kaggle_labels = pd.read_csv('design-2.csv')

In [181]:
kg_merge = features.merge(kaggle_labels, how='inner', left_on='sha', right_on='id')
kg_merge

paper_id                                       sha  \
0    47ema2dq  6a3fa8ed278df0d05c5e009521de11c72308f60b   
1    9trzqzep  eb4b8f43f68db5e493984b7e4e56d9f804d7e885   
2    hnu8gw6w  2afcf2ab2330cb56ec493f82d87fa0c5b5f076e9   
3    5ulk3euw  9f7ed2037968c63fa97eb6fc7c35e9738a654541   
4    loowpch7  de707f97b534ca340482600ed1f008b20d7b1b8e   
..        ...                                       ...   
493  dycx8i7h  2d0d272a793b99ef896547024c51f486e9552e5a   
494  p8vhi6d9  f778c6317cdc3e2c4aa7a8c7734fa13da10723eb   
495  a6i73v0o  95d9bac431797e2cf8b7294a648ceec3bd50c84b   
496  i2vg8zqc  e9dfbc4084497e74dcaf6bd9c1dbde2b0fb70802   
497  nbbcacy4  76edb6d0bd7c47765d3a89032aa610f410506988   

                                         Study Type  label  \
0                                        ['review']      1   
1              ['questionnaire', 'cross-sectional']      8   
2                       ['time series', 'clinical']      5   
3                               ['cross-sectional']      7   
4      ['prospective cohort', 'prospective cohort']      4   
..                                              ...    ...   
493                                     ['genetic']      0   
494                                ['experimental']      2   
495  ['questionnaire', 'survey', 'cross-sectional']      7   
496                    ['experimental', 'clinical']      0   
497                                  ['case study']      8   

                                           id  
0    6a3fa8ed278df0d05c5e009521de11c72308f60b  
1    eb4b8f43f68db5e493984b7e4e56d9f804d7e885  
2    2afcf2ab2330cb56ec493f82d87fa0c5b5f076e9  
3    9f7ed2037968c63fa97eb6fc7c35e9738a654541  
4    de707f97b534ca340482600ed1f008b20d7b1b8e  
..                                        ...  
493  2d0d272a793b99ef896547024c51f486e9552e5a  
494  f778c6317cdc3e2c4aa7a8c7734fa13da10723eb  
495  95d9bac431797e2cf8b7294a648ceec3bd50c84b  
496  e9dfbc4084497e74dcaf6bd9c1dbde2b0fb70802  
497  76edb6d0bd7c47765d3a89032aa610f410506988  

[498 rows x 5 columns]

Complete kg_merge annotation set by:
1. mapping labels to cw_labels
2. performing one-hot-encoding to output multi-label dataset

In [541]:
cw_labels = pd.read_csv('CoY_newlist_v2.csv')
list(cw_labels)

['Assignee',
 'cord_uid',
 'sha',
 'title',
 'url',
 'Computational',
 'Experimental - in vitro',
 'Experimental - in vivo',
 'Systematic review and/or meta-analysis',
 'Clinical-interventional',
 'Clinical-interventional.1',
 'Clinical-observational',
 'Clinical-observational.1',
 'Systematic review and/or meta-analysis.1',
 'Review',
 'Other',
 'Unnamed: 16',
 'Unnamed: 17']

In [542]:
cw_labels = cw_labels.drop(columns = ['Unnamed: 16',
 'Unnamed: 17'])

In [543]:
#Rename/Clean-up labels
cw_labels = cw_labels.rename(columns={'Clinical-interventional.1' : 'Clinical-interventional', 'Clinical-observational.1' : 'Clinical-observational', 'Systematic review and/or meta-analysis.1' : 'Systematic review and/or meta-analysis'})

In [544]:
list(cw_labels)

['Assignee',
 'cord_uid',
 'sha',
 'title',
 'url',
 'Computational',
 'Experimental - in vitro',
 'Experimental - in vivo',
 'Systematic review and/or meta-analysis',
 'Clinical-interventional',
 'Clinical-interventional',
 'Clinical-observational',
 'Clinical-observational',
 'Systematic review and/or meta-analysis',
 'Review',
 'Other']

Mapping Kaggle labels to CoronaWhy labels

0. Other -> Drop (add in dummy for now)
1. Systematic review -> Systematic review and/or meta-analysis
2. Randomized control trial -> Clinical-interventional
3. Non-randomized trial -> Clinical - interventional
4. Prospective observational -> Clinical -observational
5. Time-to-event analysis -> Clinical-observational
6. Retrospective observational -> Clinical-observational
7. Cross-sectional -> Clinical-observational
8. Case series -> Clinical-observational
9. Modeling -> Computational

In [616]:
kg_merge.explode('label')
kg_merge['label'].unique()

In [188]:
dic_map={
         1:'Systematic review and/or meta-analysis',
         2:'Clinical-interventional',
         3:'Clinical-interventional',
         4:'Clinical-observational',
         5:'Clinical-observational',
         6:'Clinical-observational',
         7:'Clinical-observational',
         8:'Clinical-observational',
         9:'Computational',
         0:'Other'
        }

In [189]:
kg_merge['mapped'] = kg_merge.apply(lambda x: dic_map[x.label], axis = 1) 
kg_merge.head()

paper_id                                       sha  \
0  47ema2dq  6a3fa8ed278df0d05c5e009521de11c72308f60b   
1  9trzqzep  eb4b8f43f68db5e493984b7e4e56d9f804d7e885   
2  hnu8gw6w  2afcf2ab2330cb56ec493f82d87fa0c5b5f076e9   
3  5ulk3euw  9f7ed2037968c63fa97eb6fc7c35e9738a654541   
4  loowpch7  de707f97b534ca340482600ed1f008b20d7b1b8e   

                                     Study Type  label  \
0                                    ['review']      1   
1          ['questionnaire', 'cross-sectional']      8   
2                   ['time series', 'clinical']      5   
3                           ['cross-sectional']      7   
4  ['prospective cohort', 'prospective cohort']      4   

                                         id  \
0  6a3fa8ed278df0d05c5e009521de11c72308f60b   
1  eb4b8f43f68db5e493984b7e4e56d9f804d7e885   
2  2afcf2ab2330cb56ec493f82d87fa0c5b5f076e9   
3  9f7ed2037968c63fa97eb6fc7c35e9738a654541   
4  de707f97b534ca340482600ed1f008b20d7b1b8e   

                                   mapped  
0  Systematic review and/or meta-analysis  
1                  Clinical-observational  
2                  Clinical-observational  
3                  Clinical-observational  
4                  Clinical-observational

In [190]:
#Drop 0. Other label
kg_merge = kg_merge[kg_merge.label != 0]
kg_merge

paper_id                                       sha  \
0    47ema2dq  6a3fa8ed278df0d05c5e009521de11c72308f60b   
1    9trzqzep  eb4b8f43f68db5e493984b7e4e56d9f804d7e885   
2    hnu8gw6w  2afcf2ab2330cb56ec493f82d87fa0c5b5f076e9   
3    5ulk3euw  9f7ed2037968c63fa97eb6fc7c35e9738a654541   
4    loowpch7  de707f97b534ca340482600ed1f008b20d7b1b8e   
..        ...                                       ...   
490  l4649du3  bb3bf36ce2af876dcbf80b6cf3598e4421c98b3e   
491  3vpoxfnv  eb720970f362e4416b73393f230c8606c837c6dc   
494  p8vhi6d9  f778c6317cdc3e2c4aa7a8c7734fa13da10723eb   
495  a6i73v0o  95d9bac431797e2cf8b7294a648ceec3bd50c84b   
497  nbbcacy4  76edb6d0bd7c47765d3a89032aa610f410506988   

                                         Study Type  label  \
0                                        ['review']      1   
1              ['questionnaire', 'cross-sectional']      8   
2                       ['time series', 'clinical']      5   
3                               ['cross-sectional']      7   
4      ['prospective cohort', 'prospective cohort']      4   
..                                              ...    ...   
490                                    ['clinical']      2   
491                                    ['clinical']      9   
494                                ['experimental']      2   
495  ['questionnaire', 'survey', 'cross-sectional']      7   
497                                  ['case study']      8   

                                           id  \
0    6a3fa8ed278df0d05c5e009521de11c72308f60b   
1    eb4b8f43f68db5e493984b7e4e56d9f804d7e885   
2    2afcf2ab2330cb56ec493f82d87fa0c5b5f076e9   
3    9f7ed2037968c63fa97eb6fc7c35e9738a654541   
4    de707f97b534ca340482600ed1f008b20d7b1b8e   
..                                        ...   
490  bb3bf36ce2af876dcbf80b6cf3598e4421c98b3e   
491  eb720970f362e4416b73393f230c8606c837c6dc   
494  f778c6317cdc3e2c4aa7a8c7734fa13da10723eb   
495  95d9bac431797e2cf8b7294a648ceec3bd50c84b   
497  76edb6d0bd7c47765d3a89032aa610f410506988   

                                     mapped  
0    Systematic review and/or meta-analysis  
1                    Clinical-observational  
2                    Clinical-observational  
3                    Clinical-observational  
4                    Clinical-observational  
..                                      ...  
490                 Clinical-interventional  
491                           Computational  
494                 Clinical-interventional  
495                  Clinical-observational  
497                  Clinical-observational  

[398 rows x 6 columns]

100 less annotations is a huge drop. 

### One-Hot Encoding

In [191]:
one_hot = pd.get_dummies(kg_merge['mapped'])
#drop mapped column as it is encoded now
kg_merge = kg_merge.drop('mapped',axis = 1)
# Join the encoded mapped to df3
kg_merge = kg_merge.join(one_hot)
kg_merge

paper_id                                       sha  \
0    47ema2dq  6a3fa8ed278df0d05c5e009521de11c72308f60b   
1    9trzqzep  eb4b8f43f68db5e493984b7e4e56d9f804d7e885   
2    hnu8gw6w  2afcf2ab2330cb56ec493f82d87fa0c5b5f076e9   
3    5ulk3euw  9f7ed2037968c63fa97eb6fc7c35e9738a654541   
4    loowpch7  de707f97b534ca340482600ed1f008b20d7b1b8e   
..        ...                                       ...   
490  l4649du3  bb3bf36ce2af876dcbf80b6cf3598e4421c98b3e   
491  3vpoxfnv  eb720970f362e4416b73393f230c8606c837c6dc   
494  p8vhi6d9  f778c6317cdc3e2c4aa7a8c7734fa13da10723eb   
495  a6i73v0o  95d9bac431797e2cf8b7294a648ceec3bd50c84b   
497  nbbcacy4  76edb6d0bd7c47765d3a89032aa610f410506988   

                                         Study Type  label  \
0                                        ['review']      1   
1              ['questionnaire', 'cross-sectional']      8   
2                       ['time series', 'clinical']      5   
3                               ['cross-sectional']      7   
4      ['prospective cohort', 'prospective cohort']      4   
..                                              ...    ...   
490                                    ['clinical']      2   
491                                    ['clinical']      9   
494                                ['experimental']      2   
495  ['questionnaire', 'survey', 'cross-sectional']      7   
497                                  ['case study']      8   

                                           id  Clinical-interventional  \
0    6a3fa8ed278df0d05c5e009521de11c72308f60b                        0   
1    eb4b8f43f68db5e493984b7e4e56d9f804d7e885                        0   
2    2afcf2ab2330cb56ec493f82d87fa0c5b5f076e9                        0   
3    9f7ed2037968c63fa97eb6fc7c35e9738a654541                        0   
4    de707f97b534ca340482600ed1f008b20d7b1b8e                        0   
..                                        ...                      ...   
490  bb3bf36ce2af876dcbf80b6cf3598e4421c98b3e                        1   
491  eb720970f362e4416b73393f230c8606c837c6dc                        0   
494  f778c6317cdc3e2c4aa7a8c7734fa13da10723eb                        1   
495  95d9bac431797e2cf8b7294a648ceec3bd50c84b                        0   
497  76edb6d0bd7c47765d3a89032aa610f410506988                        0   

     Clinical-observational  Computational  \
0                         0              0   
1                         1              0   
2                         1              0   
3                         1              0   
4                         1              0   
..                      ...            ...   
490                       0              0   
491                       0              1   
494                       0              0   
495                       1              0   
497                       1              0   

     Systematic review and/or meta-analysis  
0                                         1  
1                                         0  
2                                         0  
3                                         0  
4                                         0  
..                                      ...  
490                                       0  
491                                       0  
494                                       0  
495                                       0  
497                                       0  

[398 rows x 9 columns]

### Clean up table by dropping unnecessary columns and adding necessary columns to kg_merge to final output.

In [192]:
kg_merge = kg_merge.drop(columns = ['label', 'id'])
kg_merge

paper_id                                       sha  \
0    47ema2dq  6a3fa8ed278df0d05c5e009521de11c72308f60b   
1    9trzqzep  eb4b8f43f68db5e493984b7e4e56d9f804d7e885   
2    hnu8gw6w  2afcf2ab2330cb56ec493f82d87fa0c5b5f076e9   
3    5ulk3euw  9f7ed2037968c63fa97eb6fc7c35e9738a654541   
4    loowpch7  de707f97b534ca340482600ed1f008b20d7b1b8e   
..        ...                                       ...   
490  l4649du3  bb3bf36ce2af876dcbf80b6cf3598e4421c98b3e   
491  3vpoxfnv  eb720970f362e4416b73393f230c8606c837c6dc   
494  p8vhi6d9  f778c6317cdc3e2c4aa7a8c7734fa13da10723eb   
495  a6i73v0o  95d9bac431797e2cf8b7294a648ceec3bd50c84b   
497  nbbcacy4  76edb6d0bd7c47765d3a89032aa610f410506988   

                                         Study Type  Clinical-interventional  \
0                                        ['review']                        0   
1              ['questionnaire', 'cross-sectional']                        0   
2                       ['time series', 'clinical']                        0   
3                               ['cross-sectional']                        0   
4      ['prospective cohort', 'prospective cohort']                        0   
..                                              ...                      ...   
490                                    ['clinical']                        1   
491                                    ['clinical']                        0   
494                                ['experimental']                        1   
495  ['questionnaire', 'survey', 'cross-sectional']                        0   
497                                  ['case study']                        0   

     Clinical-observational  Computational  \
0                         0              0   
1                         1              0   
2                         1              0   
3                         1              0   
4                         1              0   
..                      ...            ...   
490                       0              0   
491                       0              1   
494                       0              0   
495                       1              0   
497                       1              0   

     Systematic review and/or meta-analysis  
0                                         1  
1                                         0  
2                                         0  
3                                         0  
4                                         0  
..                                      ...  
490                                       0  
491                                       0  
494                                       0  
495                                       0  
497                                       0  

[398 rows x 7 columns]

In [193]:
#Adding necessary columns
c = {'Experimental - in vitro': 0, 'Experimental - in vivo': 0}
kg_merge = kg_merge.assign(**c)
#Reordering columns
cols = ['paper_id', 'sha', 'Study Type', 'Computational',
 'Experimental - in vitro',
 'Experimental - in vivo',
 'Clinical-interventional',
 'Clinical-observational',
 'Systematic review and/or meta-analysis']
kg_merge = kg_merge[cols]
kg_merge

paper_id                                       sha  \
0    47ema2dq  6a3fa8ed278df0d05c5e009521de11c72308f60b   
1    9trzqzep  eb4b8f43f68db5e493984b7e4e56d9f804d7e885   
2    hnu8gw6w  2afcf2ab2330cb56ec493f82d87fa0c5b5f076e9   
3    5ulk3euw  9f7ed2037968c63fa97eb6fc7c35e9738a654541   
4    loowpch7  de707f97b534ca340482600ed1f008b20d7b1b8e   
..        ...                                       ...   
490  l4649du3  bb3bf36ce2af876dcbf80b6cf3598e4421c98b3e   
491  3vpoxfnv  eb720970f362e4416b73393f230c8606c837c6dc   
494  p8vhi6d9  f778c6317cdc3e2c4aa7a8c7734fa13da10723eb   
495  a6i73v0o  95d9bac431797e2cf8b7294a648ceec3bd50c84b   
497  nbbcacy4  76edb6d0bd7c47765d3a89032aa610f410506988   

                                         Study Type  Computational  \
0                                        ['review']              0   
1              ['questionnaire', 'cross-sectional']              0   
2                       ['time series', 'clinical']              0   
3                               ['cross-sectional']              0   
4      ['prospective cohort', 'prospective cohort']              0   
..                                              ...            ...   
490                                    ['clinical']              0   
491                                    ['clinical']              1   
494                                ['experimental']              0   
495  ['questionnaire', 'survey', 'cross-sectional']              0   
497                                  ['case study']              0   

     Experimental - in vitro  Experimental - in vivo  Clinical-interventional  \
0                          0                       0                        0   
1                          0                       0                        0   
2                          0                       0                        0   
3                          0                       0                        0   
4                          0                       0                        0   
..                       ...                     ...                      ...   
490                        0                       0                        1   
491                        0                       0                        0   
494                        0                       0                        1   
495                        0                       0                        0   
497                        0                       0                        0   

     Clinical-observational  Systematic review and/or meta-analysis  
0                         0                                       1  
1                         1                                       0  
2                         1                                       0  
3                         1                                       0  
4                         1                                       0  
..                      ...                                     ...  
490                       0                                       0  
491                       0                                       0  
494                       0                                       0  
495                       1                                       0  
497                       1                                       0  

[398 rows x 9 columns]

In [546]:
#Adding dummy columns Review and Other
c = {'Review': 0, 'Other': 0}
kg_merge = kg_merge.assign(**c)

In [548]:
kg_merge.iloc[:,3:].sum()
# total1 = []
# for i in range(0,8):
#     total1.append(kg_merge.iloc[:,3:].sum()[i])
# sum(total1) 

Computational                              37
Experimental - in vitro                     0
Experimental - in vivo                      0
Clinical-interventional                    44
Clinical-observational                    252
Systematic review and/or meta-analysis     65
Review                                      0
Other                                       0
dtype: int64

### Onto cw_labels. 

1. Merge with features.
2. Combine like columns into 1 column.
2. Drop unncessary columns.
3. Reorder columns as in kg_merge.

In [549]:
cw_labels.iloc[:,4:]

url  Computational  \
0    https://www.ncbi.nlm.nih.gov/pmc/articles/PMC7...            NaN   
1        https://doi.org/10.1016/j.vaccine.2016.04.096            NaN   
2            https://doi.org/10.1016/j.jff.2013.04.018            NaN   
3           https://doi.org/10.1016/j.cell.2006.02.007            NaN   
4    https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5...            NaN   
..                                                 ...            ...   
995  https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6...            NaN   
996  https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5...            NaN   
997      https://doi.org/10.1016/j.enbuild.2017.08.025            NaN   
998        https://doi.org/10.1016/j.virol.2012.11.002            NaN   
999  https://www.ncbi.nlm.nih.gov/pmc/articles/PMC2...            NaN   

     Experimental - in vitro  Experimental - in vivo  \
0                        NaN                     NaN   
1                        NaN                     NaN   
2                        NaN                     NaN   
3                        NaN                     NaN   
4                        NaN                     NaN   
..                       ...                     ...   
995                      NaN                     NaN   
996                      NaN                     NaN   
997                      NaN                     NaN   
998                      NaN                     NaN   
999                      NaN                     NaN   

     Systematic review and/or meta-analysis  Clinical-interventional  \
0                                       NaN                      NaN   
1                                       NaN                      NaN   
2                                       NaN                      NaN   
3                                       NaN                      NaN   
4                                       NaN                      NaN   
..                                      ...                      ...   
995                                     NaN                      NaN   
996                                     NaN                      NaN   
997                                     NaN                      NaN   
998                                     NaN                      NaN   
999                                     NaN                      NaN   

     Clinical-interventional  Clinical-observational  Clinical-observational  \
0                        NaN                     NaN                     NaN   
1                        NaN                     NaN                     NaN   
2                        NaN                     NaN                     NaN   
3                        NaN                     NaN                     NaN   
4                        NaN                     NaN                     NaN   
..                       ...                     ...                     ...   
995                      NaN                     NaN                     NaN   
996                      NaN                     NaN                     NaN   
997                      NaN                     NaN                     NaN   
998                      NaN                     NaN                     NaN   
999                      NaN                     NaN                     NaN   

     Systematic review and/or meta-analysis  Review  Other  
0                                       NaN     1.0    NaN  
1                                       1.0     NaN    NaN  
2                                       NaN     1.0    NaN  
3                                       NaN     1.0    NaN  
4                                       NaN     1.0    NaN  
..                                      ...     ...    ...  
995                                     NaN     NaN    NaN  
996                                     NaN     NaN    NaN  
997                                     NaN     NaN    NaN  
998                                     NaN     NaN    NaN  
999 

In [550]:
cw_labels.iloc[:,5:].sum()
total3 = []
for i in range(0,11):
    total3.append(cw_labels.iloc[:,5:].sum()[i])
sum(total3) 

931.0

931 total annotations. This does not mean that 931 publications are annotated since each pubication can have more than one label. The number of labels can be reduced based on how many matches there are between cw_labels and features.

In [551]:
list(cw_labels)

['Assignee',
 'cord_uid',
 'sha',
 'title',
 'url',
 'Computational',
 'Experimental - in vitro',
 'Experimental - in vivo',
 'Systematic review and/or meta-analysis',
 'Clinical-interventional',
 'Clinical-interventional',
 'Clinical-observational',
 'Clinical-observational',
 'Systematic review and/or meta-analysis',
 'Review',
 'Other']

In [552]:
#Drop empty annotations.
cw_labels.dropna(subset=['Computational',
 'Experimental - in vitro',
 'Experimental - in vivo',
 'Systematic review and/or meta-analysis',
 'Clinical-interventional',
 'Clinical-interventional',
 'Clinical-observational',
 'Clinical-observational',
 'Systematic review and/or meta-analysis',
 'Review',
 'Other'], how='all', inplace = True) 
cw_labels

Assignee  cord_uid                                       sha  \
0           Zayd  mmykzj9w  f0dd0852e4b1b5ccb3add01fc3aa561478b8be89   
1           Zayd  480bzpi1  a484db449f6d41927b645a3d5bcdd1ada691e694   
2           Zayd  n5o7u56f  862dbb7e5c850f946575d3c882f46be61d139a22   
3           Zayd  8rl4kswe  8acb82e7915763480c44bce48a261d1a3199cda0   
4           Zayd  whfyczcj  f6fdeab5faa3141b4d0ba262210e6662a7aa261a   
..           ...       ...                                       ...   
845          NaN  s5afikdu  5bf2ab79a25fdb03f50dafb0d08de60acbd50af0   
846          NaN  7bf5rx7k  de207527ab4b8826e6e8901d63e768c19691b178   
847  Julie Kurek  n6obzraw  5171ad879a46d32ccb76fcce6c39023aa836db31   
848          NaN  z36p5jo6  6aae752380943069e39342f1d86741124211c312   
849          NaN  1cqch98y  6ece7f85999f6b888f851792168ebaaed0e32b69   

                                                 title  \
0    Biological effects of HBV X protein on hepatoc...   
1    Do we have enough evidence how seasonal influe...   
2    Bioactive principles from Cordyceps sinensis: ...   
3                             Virus Entry: Open Sesame   
4    Hijacking of the Ubiquitin/Proteasome Pathway ...   
..                                                 ...   
845  Cell surface α2,3-linked sialic acid facilitat...   
846  Middle East respiratory syndrome coronavirus: ...   
847                         2010: The Year of the Lung   
848  Detection and characterisation of coronaviruse...   
849  Epidemiologic approaches used in a herd health...   

                                                   url  Computational  \
0    https://www.ncbi.nlm.nih.gov/pmc/articles/PMC7...            NaN   
1        https://doi.org/10.1016/j.vaccine.2016.04.096            NaN   
2            https://doi.org/10.1016/j.jff.2013.04.018            NaN   
3           https://doi.org/10.1016/j.cell.2006.02.007            NaN   
4    https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5...            NaN   
..                                                 ...            ...   
845  https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6...            NaN   
846  https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5...            NaN   
847              https://doi.org/10.1378/chest.10-2555            1.0   
848  https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5...            NaN   
849       https://doi.org/10.1016/0167-5877(86)90013-9            NaN   

     Experimental - in vitro  Experimental - in vivo  \
0                        NaN                     NaN   
1                        NaN                     NaN   
2                        NaN                     NaN   
3                        NaN                     NaN   
4                        NaN                     NaN   
..                       ...                     ...   
845                      1.0                     NaN   
846                      NaN                     NaN   
847                      NaN                     NaN   
848                      NaN                     1.0   
849                      NaN                     1.0   

     Systematic review and/or meta-analysis  Clinical-interventional  \
0                                       NaN                      NaN   
1                                       NaN                      NaN   
2                                       NaN                      NaN   
3                                       NaN                      NaN   
4                                       NaN                      NaN   
..                                      ...                      ...   
845                                     NaN                      NaN   
846                                     NaN                      NaN   
847                                     NaN                      NaN   
848                                     NaN                      NaN   
849                                     NaN                      NaN   

     Clinical-interventional  C

843 total full annotations.

In [553]:
cw_merge = features.merge(cw_labels, how='inner', left_on='paper_id', right_on='cord_uid')
cw_merge

paper_id                                     sha_x  \
0    gdsfkw1b  8d7400a2b387820cd391d7df8194642e50402a0c   
1    e1iaiwc6  eddc547cbba693715e4fd55e6a946e8ec7d96bc2   
2    o088rxb5  9f63ebfaab049c0968d72166761217b3aaa1fe00   
3    icp9d998  8c640872048570b0a671ec08c83ef6cbebcdd78e   
4    dh9n3j23  c7c4b98517819b787b89bfeee835280593dbf035   
..        ...                                       ...   
362  xk6tbnfu  23ead4b6087e730c7c24b626f490a75819eb038b   
363  tbwecf7o  f60a18092c9596fed480a4e872150912bf3f9215   
364  2lrq18w4  6448c25b3a8d2f818f50dbc0f3aa59d7d4ce32a1   
365  jeivw926  6bef9eb1c377ae09eaaa5213fb68e74e9b6fe37d   
366  jngto9kv  31105078a2953217223699d09c6a80d0f5edfdf6   

                            Study Type Assignee  cord_uid  \
0                           ['review']      NaN  gdsfkw1b   
1                           ['survey']      NaN  e1iaiwc6   
2                         ['clinical']      NaN  o088rxb5   
3                         ['clinical']      NaN  icp9d998   
4                    ['questionnaire']      NaN  dh9n3j23   
..                                 ...      ...       ...   
362                       ['clinical']      NaN  xk6tbnfu   
363              ['prospective study']      NaN  tbwecf7o   
364                         ['review']      NaN  2lrq18w4   
365  ['review', 'genetic', 'clinical']      NaN  jeivw926   
366                         ['review']      NaN  jngto9kv   

                                        sha_y  \
0    8d7400a2b387820cd391d7df8194642e50402a0c   
1    eddc547cbba693715e4fd55e6a946e8ec7d96bc2   
2    9f63ebfaab049c0968d72166761217b3aaa1fe00   
3    8c640872048570b0a671ec08c83ef6cbebcdd78e   
4    c7c4b98517819b787b89bfeee835280593dbf035   
..                                        ...   
362  23ead4b6087e730c7c24b626f490a75819eb038b   
363  f60a18092c9596fed480a4e872150912bf3f9215   
364  6448c25b3a8d2f818f50dbc0f3aa59d7d4ce32a1   
365  6bef9eb1c377ae09eaaa5213fb68e74e9b6fe37d   
366  31105078a2953217223699d09c6a80d0f5edfdf6   

                                                 title  \
0    Protein secretion in Lactococcus lactis : an e...   
1    A Severe Acute Respiratory Syndrome extranet: ...   
2    Pneumothorax and mortality in the mechanically...   
3    Selection of a set of reliable reference genes...   
4                  The Trojan Chicken Study, Minnesota   
..                                                 ...   
362                Bacterial Pneumonia in Older Adults   
363  Étude prospective de l’écologie virale hiverna...   
364        Pediatric Ear, Nose, and Throat Emergencies   
365  Perinatal death investigations: What is curren...   
366  Infecciones virales graves en pacientes inmuno...   

                                                   url  Computational  \
0    https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5...            NaN   
1    https://www.ncbi.nlm.nih.gov/pmc/articles/PMC1...            NaN   
2    https://www.ncbi.nlm.nih.gov/pmc/articles/PMC1...            NaN   
3    https://www.ncbi.nlm.nih.gov/pmc/articles/PMC1...            NaN   
4    https://www.ncbi.nlm.nih.gov/pmc/articles/PMC1...            NaN   
..                                                 ...            ...   
362          https://doi.org/10.1016/j.idc.2017.07.015            NaN   
363       https://doi.org/10.1016/j.arcped.2014.10.025            NaN   
364          https://doi.org/10.1016/j.pcl.2005.10.002            NaN   
365         https://doi.org/10.1016/j.siny.2017.02.005            NaN   
366        https://doi.org/10.1016/j.medin.2011.01.001            NaN   

     Experimental - in vitro  Experimental - in vivo  \
0                        NaN                     NaN   
1                        NaN                     NaN   
2                        NaN                     NaN   
3                        1.0                     NaN   
4                        NaN                     NaN   
..                       ...                     ...   
362     

Only 367 matching publications between cw_labels and features df.

In [554]:
cw_merge.iloc[:,8:]

Computational  Experimental - in vitro  Experimental - in vivo  \
0              NaN                      NaN                     NaN   
1              NaN                      NaN                     NaN   
2              NaN                      NaN                     NaN   
3              NaN                      1.0                     NaN   
4              NaN                      NaN                     NaN   
..             ...                      ...                     ...   
362            NaN                      NaN                     NaN   
363            NaN                      NaN                     NaN   
364            NaN                      NaN                     NaN   
365            NaN                      NaN                     NaN   
366            NaN                      NaN                     NaN   

     Systematic review and/or meta-analysis  Clinical-interventional  \
0                                       NaN                      NaN   
1                                       NaN                      NaN   
2                                       NaN                      NaN   
3                                       NaN                      NaN   
4                                       NaN                      NaN   
..                                      ...                      ...   
362                                     NaN                      NaN   
363                                     NaN                      NaN   
364                                     NaN                      NaN   
365                                     NaN                      NaN   
366                                     NaN                      NaN   

     Clinical-interventional  Clinical-observational  Clinical-observational  \
0                        NaN                     NaN                     NaN   
1                        NaN                     NaN                     1.0   
2                        NaN                     NaN                     1.0   
3                        NaN                     NaN                     NaN   
4                        NaN                     NaN                     1.0   
..                       ...                     ...                     ...   
362                      NaN                     NaN                     NaN   
363                      NaN                     NaN                     NaN   
364                      NaN                     NaN                     NaN   
365                      NaN                     NaN                     NaN   
366                      NaN                     NaN                     NaN   

     Systematic review and/or meta-analysis  Review  Other  
0                                       1.0     NaN    NaN  
1                                       NaN     NaN    NaN  
2                                       NaN     NaN    NaN  
3                                       NaN     NaN    NaN  
4                                       NaN     NaN    NaN  
..                                      ...     ...    ...  
362                                     NaN     NaN    1.0  
363                                     NaN     NaN    1.0  
364                                     NaN     1.0    NaN  
365                                     NaN     1.0    NaN  
366                                     NaN     1.0    1.0  

[367 rows x 11 columns]

In [435]:
#cw_merge['Clinical-observational'] = cw_merge['Clinical-observational'].astype('float64')

In [555]:
cw_merge.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 367 entries, 0 to 366
Data columns (total 19 columns):
 #   Column                                  Non-Null Count  Dtype  
---  ------                                  --------------  -----  
 0   paper_id                                367 non-null    object 
 1   sha_x                                   367 non-null    object 
 2   Study Type                              367 non-null    object 
 3   Assignee                                20 non-null     object 
 4   cord_uid                                367 non-null    object 
 5   sha_y                                   367 non-null    object 
 6   title                                   367 non-null    object 
 7   url                                     367 non-null    object 
 8   Computational                           23 non-null     float64
 9   Experimental - in vitro                 61 non-null     float64
 10  Experimental - in vivo                  52 non-null     float6

In [556]:
cw_merge.iloc[:,8:].sum()

Computational                             23.0
Experimental - in vitro                   61.0
Experimental - in vivo                    52.0
Systematic review and/or meta-analysis     9.0
Clinical-interventional                    6.0
Clinical-interventional                    2.0
Clinical-observational                    31.0
Clinical-observational                    61.0
Systematic review and/or meta-analysis     8.0
Review                                    83.0
Other                                     72.0
dtype: float64

In [557]:
cw_merge.iloc[:,8:].sum()[0]

23.0

In [558]:
#Check to see how many labels per column.
cw_merge.iloc[:,8:].sum()
total = []
for i in range(0,11):
    total.append(cw_merge.iloc[:,8:].sum()[i])
sum(total)

408.0

Total anotations/label prior to .sum() : 408. Will lose a bunch after combining columns together.

In [559]:
cw_merge = cw_merge.groupby(cw_merge.columns, axis=1).sum()
cw_merge

Assignee  Clinical-interventional  Clinical-observational  Computational  \
0          0                      0.0                     0.0            0.0   
1          0                      0.0                     1.0            0.0   
2          0                      0.0                     1.0            0.0   
3          0                      0.0                     0.0            0.0   
4          0                      0.0                     1.0            0.0   
..       ...                      ...                     ...            ...   
362        0                      0.0                     0.0            0.0   
363        0                      0.0                     0.0            0.0   
364        0                      0.0                     0.0            0.0   
365        0                      0.0                     0.0            0.0   
366        0                      0.0                     0.0            0.0   

     Experimental - in vitro  Experimental - in vivo  Other  Review  \
0                        0.0                     0.0    0.0     0.0   
1                        0.0                     0.0    0.0     0.0   
2                        0.0                     0.0    0.0     0.0   
3                        1.0                     0.0    0.0     0.0   
4                        0.0                     0.0    0.0     0.0   
..                       ...                     ...    ...     ...   
362                      0.0                     0.0    1.0     0.0   
363                      0.0                     0.0    1.0     0.0   
364                      0.0                     0.0    0.0     1.0   
365                      0.0                     0.0    0.0     1.0   
366                      0.0                     0.0    1.0     1.0   

                            Study Type  \
0                           ['review']   
1                           ['survey']   
2                         ['clinical']   
3                         ['clinical']   
4                    ['questionnaire']   
..                                 ...   
362                       ['clinical']   
363              ['prospective study']   
364                         ['review']   
365  ['review', 'genetic', 'clinical']   
366                         ['review']   

     Systematic review and/or meta-analysis  cord_uid  paper_id  \
0                                       1.0  gdsfkw1b  gdsfkw1b   
1                                       0.0  e1iaiwc6  e1iaiwc6   
2                                       0.0  o088rxb5  o088rxb5   
3                                       0.0  icp9d998  icp9d998   
4                                       0.0  dh9n3j23  dh9n3j23   
..                                      ...       ...       ...   
362                                     0.0  xk6tbnfu  xk6tbnfu   
363                                     0.0  tbwecf7o  tbwecf7o   
364                                     0.0  2lrq18w4  2lrq18w4   
365                                     0.0  jeivw926  jeivw926   
366                                     0.0  jngto9kv  jngto9kv   

                                        sha_x  \
0    8d7400a2b387820cd391d7df8194642e50402a0c   
1    eddc547cbba693715e4fd55e6a946e8ec7d96bc2   
2    9f63ebfaab049c0968d72166761217b3aaa1fe00   
3    8c640872048570b0a671ec08c83ef6cbebcdd78e   
4    c7c4b98517819b787b89bfeee835280593dbf035   
..                                        ...   
362  23ead4b6087e730c7c24b626f490a75819eb038b   
363  f60a18092c9596fed480a4e872150912bf3f9215   
364  6448c25b3a8d2f818f50dbc0f3aa59d7d4ce32a1   
365  6bef9eb1c377ae09eaaa5213fb68e74e9b6fe37d   
366  31105078a2953217223699d09c6a80d0f5edfdf6   

                                        sha_y  \
0    8d7400a2b387820cd391d7df8194642e50402a0c   
1    eddc547cbba693715e4fd55e6a946e8ec7d96bc2   
2    9f63ebfaab049c0968d72166761217b3aaa1fe00   
3    8c640872048570b0a671ec08c83ef6cbebcdd78e   
4    c7c4b98517819b787b89bfeee835280593dbf035 

In [561]:
cw_merge = cw_merge[['Assignee','cord_uid','paper_id','sha_x','sha_y','title','url','Study Type','Computational',
 'Experimental - in vitro',
 'Experimental - in vivo',
 'Clinical-interventional',
 'Clinical-observational',
 'Systematic review and/or meta-analysis',
 'Review',
 'Other']]

In [562]:
cw_merge

Assignee  cord_uid  paper_id                                     sha_x  \
0          0  gdsfkw1b  gdsfkw1b  8d7400a2b387820cd391d7df8194642e50402a0c   
1          0  e1iaiwc6  e1iaiwc6  eddc547cbba693715e4fd55e6a946e8ec7d96bc2   
2          0  o088rxb5  o088rxb5  9f63ebfaab049c0968d72166761217b3aaa1fe00   
3          0  icp9d998  icp9d998  8c640872048570b0a671ec08c83ef6cbebcdd78e   
4          0  dh9n3j23  dh9n3j23  c7c4b98517819b787b89bfeee835280593dbf035   
..       ...       ...       ...                                       ...   
362        0  xk6tbnfu  xk6tbnfu  23ead4b6087e730c7c24b626f490a75819eb038b   
363        0  tbwecf7o  tbwecf7o  f60a18092c9596fed480a4e872150912bf3f9215   
364        0  2lrq18w4  2lrq18w4  6448c25b3a8d2f818f50dbc0f3aa59d7d4ce32a1   
365        0  jeivw926  jeivw926  6bef9eb1c377ae09eaaa5213fb68e74e9b6fe37d   
366        0  jngto9kv  jngto9kv  31105078a2953217223699d09c6a80d0f5edfdf6   

                                        sha_y  \
0    8d7400a2b387820cd391d7df8194642e50402a0c   
1    eddc547cbba693715e4fd55e6a946e8ec7d96bc2   
2    9f63ebfaab049c0968d72166761217b3aaa1fe00   
3    8c640872048570b0a671ec08c83ef6cbebcdd78e   
4    c7c4b98517819b787b89bfeee835280593dbf035   
..                                        ...   
362  23ead4b6087e730c7c24b626f490a75819eb038b   
363  f60a18092c9596fed480a4e872150912bf3f9215   
364  6448c25b3a8d2f818f50dbc0f3aa59d7d4ce32a1   
365  6bef9eb1c377ae09eaaa5213fb68e74e9b6fe37d   
366  31105078a2953217223699d09c6a80d0f5edfdf6   

                                                 title  \
0    Protein secretion in Lactococcus lactis : an e...   
1    A Severe Acute Respiratory Syndrome extranet: ...   
2    Pneumothorax and mortality in the mechanically...   
3    Selection of a set of reliable reference genes...   
4                  The Trojan Chicken Study, Minnesota   
..                                                 ...   
362                Bacterial Pneumonia in Older Adults   
363  Étude prospective de l’écologie virale hiverna...   
364        Pediatric Ear, Nose, and Throat Emergencies   
365  Perinatal death investigations: What is curren...   
366  Infecciones virales graves en pacientes inmuno...   

                                                   url  \
0    https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5...   
1    https://www.ncbi.nlm.nih.gov/pmc/articles/PMC1...   
2    https://www.ncbi.nlm.nih.gov/pmc/articles/PMC1...   
3    https://www.ncbi.nlm.nih.gov/pmc/articles/PMC1...   
4    https://www.ncbi.nlm.nih.gov/pmc/articles/PMC1...   
..                                                 ...   
362          https://doi.org/10.1016/j.idc.2017.07.015   
363       https://doi.org/10.1016/j.arcped.2014.10.025   
364          https://doi.org/10.1016/j.pcl.2005.10.002   
365         https://doi.org/10.1016/j.siny.2017.02.005   
366        https://doi.org/10.1016/j.medin.2011.01.001   

                            Study Type  Computational  \
0                           ['review']            0.0   
1                           ['survey']            0.0   
2                         ['clinical']            0.0   
3                         ['clinical']            0.0   
4                    ['questionnaire']            0.0   
..                                 ...            ...   
362                       ['clinical']            0.0   
363              ['prospective study']            0.0   
364                         ['review']            0.0   
365  ['review', 'genetic', 'clinical']            0.0   
366                         ['review']            0.0   

     Experimental - in vitro  Experimental - in vivo  Clinical-interventional  \
0                        0.0                     0.0                      0.0   
1                        0.0                     0.0                      0.0   
2                        0.0                     0.0                      0.0   
3                        1.0                     0.0                      0

In [563]:
cw_merge.iloc[:,8:].sum()
total = []
for i in range(0,8):
    total.append(cw_merge.iloc[:,8:].sum()[i])
sum(total)

408.0

Great! Numbers were preserved after identical columns were combined together.

In [564]:
cw_merge[cw_merge['Clinical-interventional'] > 1]

Empty DataFrame
Columns: [Assignee, cord_uid, paper_id, sha_x, sha_y, title, url, Study Type, Computational, Experimental - in vitro, Experimental - in vivo, Clinical-interventional, Clinical-observational, Systematic review and/or meta-analysis, Review, Other]
Index: []

In [565]:
cw_merge[cw_merge['Clinical-observational'] > 1]

Empty DataFrame
Columns: [Assignee, cord_uid, paper_id, sha_x, sha_y, title, url, Study Type, Computational, Experimental - in vitro, Experimental - in vivo, Clinical-interventional, Clinical-observational, Systematic review and/or meta-analysis, Review, Other]
Index: []

In [566]:
cw_merge[cw_merge['Computational'] > 1]

Empty DataFrame
Columns: [Assignee, cord_uid, paper_id, sha_x, sha_y, title, url, Study Type, Computational, Experimental - in vitro, Experimental - in vivo, Clinical-interventional, Clinical-observational, Systematic review and/or meta-analysis, Review, Other]
Index: []

In [567]:
cw_merge[cw_merge['Experimental - in vitro'] > 1]

Empty DataFrame
Columns: [Assignee, cord_uid, paper_id, sha_x, sha_y, title, url, Study Type, Computational, Experimental - in vitro, Experimental - in vivo, Clinical-interventional, Clinical-observational, Systematic review and/or meta-analysis, Review, Other]
Index: []

In [568]:
cw_merge[cw_merge['Experimental - in vivo'] > 1]

Empty DataFrame
Columns: [Assignee, cord_uid, paper_id, sha_x, sha_y, title, url, Study Type, Computational, Experimental - in vitro, Experimental - in vivo, Clinical-interventional, Clinical-observational, Systematic review and/or meta-analysis, Review, Other]
Index: []

In [569]:
cw_merge[cw_merge['Systematic review and/or meta-analysis'] > 1]

Empty DataFrame
Columns: [Assignee, cord_uid, paper_id, sha_x, sha_y, title, url, Study Type, Computational, Experimental - in vitro, Experimental - in vivo, Clinical-interventional, Clinical-observational, Systematic review and/or meta-analysis, Review, Other]
Index: []

In [570]:
cw_merge = cw_merge.drop(columns = [
                      'Assignee',
                      'cord_uid',
                      'sha_y',
                      'title',
                      'url'])

In [571]:
cw_merge = cw_merge.rename(columns={'sha_x': 'sha'})
cw_merge

paper_id                                       sha  \
0    gdsfkw1b  8d7400a2b387820cd391d7df8194642e50402a0c   
1    e1iaiwc6  eddc547cbba693715e4fd55e6a946e8ec7d96bc2   
2    o088rxb5  9f63ebfaab049c0968d72166761217b3aaa1fe00   
3    icp9d998  8c640872048570b0a671ec08c83ef6cbebcdd78e   
4    dh9n3j23  c7c4b98517819b787b89bfeee835280593dbf035   
..        ...                                       ...   
362  xk6tbnfu  23ead4b6087e730c7c24b626f490a75819eb038b   
363  tbwecf7o  f60a18092c9596fed480a4e872150912bf3f9215   
364  2lrq18w4  6448c25b3a8d2f818f50dbc0f3aa59d7d4ce32a1   
365  jeivw926  6bef9eb1c377ae09eaaa5213fb68e74e9b6fe37d   
366  jngto9kv  31105078a2953217223699d09c6a80d0f5edfdf6   

                            Study Type  Computational  \
0                           ['review']            0.0   
1                           ['survey']            0.0   
2                         ['clinical']            0.0   
3                         ['clinical']            0.0   
4                    ['questionnaire']            0.0   
..                                 ...            ...   
362                       ['clinical']            0.0   
363              ['prospective study']            0.0   
364                         ['review']            0.0   
365  ['review', 'genetic', 'clinical']            0.0   
366                         ['review']            0.0   

     Experimental - in vitro  Experimental - in vivo  Clinical-interventional  \
0                        0.0                     0.0                      0.0   
1                        0.0                     0.0                      0.0   
2                        0.0                     0.0                      0.0   
3                        1.0                     0.0                      0.0   
4                        0.0                     0.0                      0.0   
..                       ...                     ...                      ...   
362                      0.0                     0.0                      0.0   
363                      0.0                     0.0                      0.0   
364                      0.0                     0.0                      0.0   
365                      0.0                     0.0                      0.0   
366                      0.0                     0.0                      0.0   

     Clinical-observational  Systematic review and/or meta-analysis  Review  \
0                       0.0                                     1.0     0.0   
1                       1.0                                     0.0     0.0   
2                       1.0                                     0.0     0.0   
3                       0.0                                     0.0     0.0   
4                       1.0                                     0.0     0.0   
..                      ...                                     ...     ...   
362                     0.0                                     0.0     0.0   
363                     0.0                                     0.0     0.0   
364                     0.0                                     0.0     1.0   
365                     0.0                                     0.0     1.0   
366                     0.0                                     0.0     1.0   

     Other  
0      0.0  
1      0.0  
2      0.0  
3      0.0  
4      0.0  
..     ...  
362    1.0  
363    1.0  
364    0.0  
365    0.0  
366    1.0  

[367 rows x 11 columns]

## Now, onto PubMed annotations. Need to:

1. Make sure pm_labels have label per row (ideally 1.0)
2. Merge pm_labels to features
3. Make sure there is still labels per row despite reduction in dataset
4. Merge any same name columns and reconcile values >1

4. (If needed, Change False/True to 0/1)

5. rename label columns to those corresponding to ones in kg_merge/cw_merge
6. Reorder column names

In [573]:
pm_labels = pd.read_csv('metadata_extra_info_from_pubmed_db.csv')
pm_labels

is_rct  is_systematic_reivew  is_review  is_meta_analysis  \
0       False                 False      False             False   
1       False                 False      False             False   
2       False                 False      False             False   
3       False                 False      False             False   
4       False                 False      False             False   
...       ...                   ...        ...               ...   
57361   False                 False      False             False   
57362   False                 False       True             False   
57363   False                 False      False             False   
57364   False                 False       True             False   
57365   False                 False      False             False   

       is_observational_study  is_case_series  is_clincal_trial  cord_uid  \
0                       False           False             False  zjufx4fo   
1                       False           False             False  ymceytj3   
2                       False           False             False  wzj2glte   
3                       False           False             False  2sfqsfm1   
4                       False           False             False  i0zym7iq   
...                       ...             ...               ...       ...   
57361                   False           False             False  rn4gm3sc   
57362                   False           False             False  l5oecoot   
57363                   False           False             False  i4acg2ex   
57364                   False           False             False  rve0w3dg   
57365                   False           False             False  ut7dlyh8   

       pubmed_id  
0       11742998  
1       11980704  
2       11447125  
3       12093723  
4       12456663  
...          ...  
57361   32105468  
57362   16931122  
57363   18035462  
57364    8395326  
57365   19748425  

[57366 rows x 9 columns]

In [574]:
d = {True:1, False:np.nan}
pm_labels = pm_labels.applymap(lambda x: d.get(x,x))
pm_labels

is_rct  is_systematic_reivew  is_review  is_meta_analysis  \
0         NaN                   NaN        NaN               NaN   
1         NaN                   NaN        NaN               NaN   
2         NaN                   NaN        NaN               NaN   
3         NaN                   NaN        NaN               NaN   
4         NaN                   NaN        NaN               NaN   
...       ...                   ...        ...               ...   
57361     NaN                   NaN        NaN               NaN   
57362     NaN                   NaN        1.0               NaN   
57363     NaN                   NaN        NaN               NaN   
57364     NaN                   NaN        1.0               NaN   
57365     NaN                   NaN        NaN               NaN   

       is_observational_study  is_case_series  is_clincal_trial  cord_uid  \
0                         NaN             NaN               NaN  zjufx4fo   
1                         NaN             NaN               NaN  ymceytj3   
2                         NaN             NaN               NaN  wzj2glte   
3                         NaN             NaN               NaN  2sfqsfm1   
4                         NaN             NaN               NaN  i0zym7iq   
...                       ...             ...               ...       ...   
57361                     NaN             NaN               NaN  rn4gm3sc   
57362                     NaN             NaN               NaN  l5oecoot   
57363                     NaN             NaN               NaN  i4acg2ex   
57364                     NaN             NaN               NaN  rve0w3dg   
57365                     NaN             NaN               NaN  ut7dlyh8   

        pubmed_id  
0      11742998.0  
1      11980704.0  
2      11447125.0  
3      12093723.0  
4      12456663.0  
...           ...  
57361  32105468.0  
57362  16931122.0  
57363  18035462.0  
57364   8395326.0  
57365  19748425.0  

[57366 rows x 9 columns]

In [575]:
list(pm_labels)

['is_rct',
 'is_systematic_reivew',
 'is_review',
 'is_meta_analysis',
 'is_observational_study',
 'is_case_series',
 'is_clincal_trial',
 'cord_uid',
 'pubmed_id']

In [576]:
#Drop all rows that have NaN's across all labels
pm_labels.dropna(subset=['is_rct',
 'is_systematic_reivew',
 'is_review',
 'is_meta_analysis',
 'is_observational_study',
 'is_case_series',
 'is_clincal_trial'], how='all', inplace = True) 
pm_labels

is_rct  is_systematic_reivew  is_review  is_meta_analysis  \
6         NaN                   NaN        1.0               NaN   
40        NaN                   1.0        1.0               NaN   
47        NaN                   NaN        NaN               NaN   
54        NaN                   NaN        1.0               NaN   
76        NaN                   NaN        1.0               NaN   
...       ...                   ...        ...               ...   
57343     1.0                   NaN        NaN               NaN   
57355     NaN                   NaN        1.0               NaN   
57356     NaN                   NaN        1.0               NaN   
57362     NaN                   NaN        1.0               NaN   
57364     NaN                   NaN        1.0               NaN   

       is_observational_study  is_case_series  is_clincal_trial  cord_uid  \
6                         NaN             NaN               NaN  gi6uaa83   
40                        NaN             NaN               NaN  47ema2dq   
47                        NaN             NaN               1.0  mtmgur1u   
54                        NaN             NaN               NaN  jh9e85c0   
76                        NaN             NaN               NaN  0fitbwuv   
...                       ...             ...               ...       ...   
57343                     NaN             NaN               1.0  y8u5jl70   
57355                     NaN             NaN               NaN  r35fd6v0   
57356                     NaN             NaN               NaN  t2vl0cw6   
57362                     NaN             NaN               NaN  l5oecoot   
57364                     NaN             NaN               NaN  rve0w3dg   

        pubmed_id  
6      12734001.0  
40     15518593.0  
47     15638943.0  
54     15661082.0  
76     15833113.0  
...           ...  
57343  25922328.0  
57355  28242560.0  
57356  28377208.0  
57362  16931122.0  
57364   8395326.0  

[8284 rows x 9 columns]

Huge reduction in labels! At least have ~8,000 and not around 1000.

In [577]:
pm_merge = features.merge(pm_labels, how='inner', left_on='paper_id', right_on='cord_uid')
pm_merge

paper_id                                       sha  \
0     gi6uaa83  8ae137c8da1607b3a8e4c946c07ca8bda67f88ac   
1     47ema2dq  6a3fa8ed278df0d05c5e009521de11c72308f60b   
2     mtmgur1u  18c21db94a22f1358057c6d797164ffe1585b395   
3     jh9e85c0  d16e1bd4c6cae1bb55dbc695c5e2ba5105a13921   
4     0fitbwuv  d0c6b0c2d387baae89eb2898969913218b3bedff   
...        ...                                       ...   
5742  swafz389  3941c1d823c466b3c789439259c5030ba8f8aaa3   
5743  bupfw5la  e8fb3f9b3a3acda9ebb5cc8ad74624a68c78bbb1   
5744  1k8v0luz  417cc66866cbe8108fbc116d45ec1d5d2ffbe16e   
5745  v6qry3o6  c2d51fee1e73856e4c891437f8349da3eadbe363   
5746  jngto9kv  31105078a2953217223699d09c6a80d0f5edfdf6   

                        Study Type  is_rct  is_systematic_reivew  is_review  \
0         ['genetic', 'histories']     NaN                   NaN        1.0   
1                       ['review']     NaN                   1.0        1.0   
2                     ['clinical']     NaN                   NaN        NaN   
3     ['experimental', 'clinical']     NaN                   NaN        1.0   
4                       ['review']     NaN                   NaN        1.0   
...                            ...     ...                   ...        ...   
5742                  ['clinical']     NaN                   NaN        1.0   
5743                  ['clinical']     NaN                   NaN        1.0   
5744                  ['clinical']     NaN                   NaN        NaN   
5745                  ['clinical']     NaN                   NaN        NaN   
5746                    ['review']     NaN                   NaN        1.0   

      is_meta_analysis  is_observational_study  is_case_series  \
0                  NaN                     NaN             NaN   
1                  NaN                     NaN             NaN   
2                  NaN                     NaN             NaN   
3                  NaN                     NaN             NaN   
4                  NaN                     NaN             NaN   
...                ...                     ...             ...   
5742               NaN                     NaN             NaN   
5743               NaN                     NaN             NaN   
5744               NaN                     1.0             NaN   
5745               NaN                     NaN             NaN   
5746               NaN                     NaN             NaN   

      is_clincal_trial  cord_uid   pubmed_id  
0                  NaN  gi6uaa83  12734001.0  
1                  NaN  47ema2dq  15518593.0  
2                  1.0  mtmgur1u  15638943.0  
3                  NaN  jh9e85c0  15661082.0  
4                  NaN  0fitbwuv  15833113.0  
...                ...       ...         ...  
5742               NaN  swafz389  28062161.0  
5743               NaN  bupfw5la  31027659.0  
5744               NaN  1k8v0luz  28734862.0  
5745               1.0  v6qry3o6  22230592.0  
5746               NaN  jngto9kv  21353339.0  

[5747 rows x 12 columns]

Once again, huge reduction. At least, there are >1000 labels.

In [578]:
pm_merge.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 5747 entries, 0 to 5746
Data columns (total 12 columns):
 #   Column                  Non-Null Count  Dtype  
---  ------                  --------------  -----  
 0   paper_id                5747 non-null   object 
 1   sha                     5216 non-null   object 
 2   Study Type              5747 non-null   object 
 3   is_rct                  163 non-null    float64
 4   is_systematic_reivew    173 non-null    float64
 5   is_review               4996 non-null   float64
 6   is_meta_analysis        100 non-null    float64
 7   is_observational_study  97 non-null     float64
 8   is_case_series          335 non-null    float64
 9   is_clincal_trial        278 non-null    float64
 10  cord_uid                5747 non-null   object 
 11  pubmed_id               5747 non-null   float64
dtypes: float64(8), object(4)
memory usage: 583.7+ KB


Mapping pm_merge labels to cw_merge labels

1. 'is_rct' -> Clinical-interventional
2. 'is_systematic_reivew' -> Systematic review and/or meta-analysis
3. 'is_review' -> Other
4. 'is_meta_analysis' -> Systematic review and/or meta-analysis
5. 'is_observational_study' -> Clinical-observational
6. 'is_case_series' -> Clinical-observational
7. 'is_clincal_trial' -> Clinical-interventional

In [579]:
pm_merge = pm_merge.rename(columns=
{'is_rct': 'Clinical-interventional', 'is_systematic_reivew' : 'Systematic review and/or meta-analysis', 'is_review' : 'Other', 'is_meta_analysis' : 'Systematic review and/or meta-analysis', 'is_observational_study' : 'Clinical-observational', 'is_case_series' : 'Clinical-observational', 'is_clincal_trial' : 'Clinical-interventional'})

In [580]:
pm_merge

paper_id                                       sha  \
0     gi6uaa83  8ae137c8da1607b3a8e4c946c07ca8bda67f88ac   
1     47ema2dq  6a3fa8ed278df0d05c5e009521de11c72308f60b   
2     mtmgur1u  18c21db94a22f1358057c6d797164ffe1585b395   
3     jh9e85c0  d16e1bd4c6cae1bb55dbc695c5e2ba5105a13921   
4     0fitbwuv  d0c6b0c2d387baae89eb2898969913218b3bedff   
...        ...                                       ...   
5742  swafz389  3941c1d823c466b3c789439259c5030ba8f8aaa3   
5743  bupfw5la  e8fb3f9b3a3acda9ebb5cc8ad74624a68c78bbb1   
5744  1k8v0luz  417cc66866cbe8108fbc116d45ec1d5d2ffbe16e   
5745  v6qry3o6  c2d51fee1e73856e4c891437f8349da3eadbe363   
5746  jngto9kv  31105078a2953217223699d09c6a80d0f5edfdf6   

                        Study Type  Clinical-interventional  \
0         ['genetic', 'histories']                      NaN   
1                       ['review']                      NaN   
2                     ['clinical']                      NaN   
3     ['experimental', 'clinical']                      NaN   
4                       ['review']                      NaN   
...                            ...                      ...   
5742                  ['clinical']                      NaN   
5743                  ['clinical']                      NaN   
5744                  ['clinical']                      NaN   
5745                  ['clinical']                      NaN   
5746                    ['review']                      NaN   

      Systematic review and/or meta-analysis  Other  \
0                                        NaN    1.0   
1                                        1.0    1.0   
2                                        NaN    NaN   
3                                        NaN    1.0   
4                                        NaN    1.0   
...                                      ...    ...   
5742                                     NaN    1.0   
5743                                     NaN    1.0   
5744                                     NaN    NaN   
5745                                     NaN    NaN   
5746                                     NaN    1.0   

      Systematic review and/or meta-analysis  Clinical-observational  \
0                                        NaN                     NaN   
1                                        NaN                     NaN   
2                                        NaN                     NaN   
3                                        NaN                     NaN   
4                                        NaN                     NaN   
...                                      ...                     ...   
5742                                     NaN                     NaN   
5743                                     NaN                     NaN   
5744                                     NaN                     1.0   
5745                                     NaN                     NaN   
5746                                     NaN                     NaN   

      Clinical-observational  Clinical-interventional  cord_uid   pubmed_id  
0                        NaN                      NaN  gi6uaa83  12734001.0  
1                        NaN                      NaN  47ema2dq  15518593.0  
2                        NaN                      1.0  mtmgur1u  15638943.0  
3                        NaN                      NaN  jh9e85c0  15661082.0  
4                        NaN                      NaN  0fitbwuv  15833113.0  
...                      ...                      ...       ...         ...  
5742                     NaN                      NaN  swafz389  28062161.0  
5743                     NaN                      NaN  bupfw5la  31027659.0  
5744                     NaN                      NaN  1k8v0luz  28734862.0  
5745                     NaN                      1.0  v6qry3o6  22230592.0  
5746                     NaN                      NaN  jngto9kv  21353339.0  

[5747 rows x 12 columns]

In [582]:
pm_merge = pm_merge.drop(columns = ['cord_uid', 'pubmed_id'])

In [583]:
pm_merge.iloc[:,3:].sum()

Clinical-interventional                    163.0
Systematic review and/or meta-analysis     173.0
Other                                     4996.0
Systematic review and/or meta-analysis     100.0
Clinical-observational                      97.0
Clinical-observational                     335.0
Clinical-interventional                    278.0
dtype: float64

In [586]:
total3 = []
for i in range(0,7):
    total3.append(pm_merge.iloc[:,3:].sum()[i])
sum(total3) 

6142.0

In [587]:
pm_merge = pm_merge.groupby(pm_merge.columns, axis=1).sum()
pm_merge

Clinical-interventional  Clinical-observational  Other  \
0                         0.0                     0.0    1.0   
1                         0.0                     0.0    1.0   
2                         1.0                     0.0    0.0   
3                         0.0                     0.0    1.0   
4                         0.0                     0.0    1.0   
...                       ...                     ...    ...   
5742                      0.0                     0.0    1.0   
5743                      0.0                     0.0    1.0   
5744                      0.0                     1.0    0.0   
5745                      1.0                     0.0    0.0   
5746                      0.0                     0.0    1.0   

                        Study Type  Systematic review and/or meta-analysis  \
0         ['genetic', 'histories']                                     0.0   
1                       ['review']                                     1.0   
2                     ['clinical']                                     0.0   
3     ['experimental', 'clinical']                                     0.0   
4                       ['review']                                     0.0   
...                            ...                                     ...   
5742                  ['clinical']                                     0.0   
5743                  ['clinical']                                     0.0   
5744                  ['clinical']                                     0.0   
5745                  ['clinical']                                     0.0   
5746                    ['review']                                     0.0   

      paper_id                                       sha  
0     gi6uaa83  8ae137c8da1607b3a8e4c946c07ca8bda67f88ac  
1     47ema2dq  6a3fa8ed278df0d05c5e009521de11c72308f60b  
2     mtmgur1u  18c21db94a22f1358057c6d797164ffe1585b395  
3     jh9e85c0  d16e1bd4c6cae1bb55dbc695c5e2ba5105a13921  
4     0fitbwuv  d0c6b0c2d387baae89eb2898969913218b3bedff  
...        ...                                       ...  
5742  swafz389  3941c1d823c466b3c789439259c5030ba8f8aaa3  
5743  bupfw5la  e8fb3f9b3a3acda9ebb5cc8ad74624a68c78bbb1  
5744  1k8v0luz  417cc66866cbe8108fbc116d45ec1d5d2ffbe16e  
5745  v6qry3o6  c2d51fee1e73856e4c891437f8349da3eadbe363  
5746  jngto9kv  31105078a2953217223699d09c6a80d0f5edfdf6  

[5747 rows x 7 columns]

In [588]:
list(pm_merge)

['Clinical-interventional',
 'Clinical-observational',
 'Other',
 'Study Type',
 'Systematic review and/or meta-analysis',
 'paper_id',
 'sha']

In [589]:
cols = ['paper_id',
'sha',
'Study Type',
'Clinical-interventional',
'Clinical-observational',
'Systematic review and/or meta-analysis',
'Other']
pm_merge = pm_merge[cols]
pm_merge

paper_id                                       sha  \
0     gi6uaa83  8ae137c8da1607b3a8e4c946c07ca8bda67f88ac   
1     47ema2dq  6a3fa8ed278df0d05c5e009521de11c72308f60b   
2     mtmgur1u  18c21db94a22f1358057c6d797164ffe1585b395   
3     jh9e85c0  d16e1bd4c6cae1bb55dbc695c5e2ba5105a13921   
4     0fitbwuv  d0c6b0c2d387baae89eb2898969913218b3bedff   
...        ...                                       ...   
5742  swafz389  3941c1d823c466b3c789439259c5030ba8f8aaa3   
5743  bupfw5la  e8fb3f9b3a3acda9ebb5cc8ad74624a68c78bbb1   
5744  1k8v0luz  417cc66866cbe8108fbc116d45ec1d5d2ffbe16e   
5745  v6qry3o6  c2d51fee1e73856e4c891437f8349da3eadbe363   
5746  jngto9kv  31105078a2953217223699d09c6a80d0f5edfdf6   

                        Study Type  Clinical-interventional  \
0         ['genetic', 'histories']                      0.0   
1                       ['review']                      0.0   
2                     ['clinical']                      1.0   
3     ['experimental', 'clinical']                      0.0   
4                       ['review']                      0.0   
...                            ...                      ...   
5742                  ['clinical']                      0.0   
5743                  ['clinical']                      0.0   
5744                  ['clinical']                      0.0   
5745                  ['clinical']                      1.0   
5746                    ['review']                      0.0   

      Clinical-observational  Systematic review and/or meta-analysis  Other  
0                        0.0                                     0.0    1.0  
1                        0.0                                     1.0    1.0  
2                        0.0                                     0.0    0.0  
3                        0.0                                     0.0    1.0  
4                        0.0                                     0.0    1.0  
...                      ...                                     ...    ...  
5742                     0.0                                     0.0    1.0  
5743                     0.0                                     0.0    1.0  
5744                     1.0                                     0.0    0.0  
5745                     0.0                                     0.0    0.0  
5746                     0.0                                     0.0    1.0  

[5747 rows x 7 columns]

In [590]:
pm_merge.iloc[:,3:].sum()

Clinical-interventional                    441.0
Clinical-observational                     432.0
Systematic review and/or meta-analysis     273.0
Other                                     4996.0
dtype: float64

In [591]:
total4 = []
for i in range(0,4):
    total4.append(pm_merge.iloc[:,3:].sum()[i])
sum(total4) 

6142.0

In [602]:
#Make sure all values in pm_merge label columns are 0/1
pm_merge[pm_merge['Clinical-interventional'] > 1]

Empty DataFrame
Columns: [paper_id, sha, Study Type, Clinical-interventional, Clinical-observational, Systematic review and/or meta-analysis, Other]
Index: []

In [593]:
pm_merge[pm_merge['Clinical-observational'] > 1]

paper_id                                       sha  \
4762  6tq0kcfd  8186586de026807b862de876abfeef625a9a78cb   

                  Study Type  Clinical-interventional  Clinical-observational  \
4762  ['review', 'clinical']                      0.0                     2.0   

      Systematic review and/or meta-analysis  Other  
4762                                     0.0    0.0

In [594]:
pm_merge[pm_merge['Systematic review and/or meta-analysis'] > 1]

paper_id                                                sha  \
47    67bhdlzy                                                  0   
164   ox4dwecj           04d9df812fd77e1231263d42ab45e570cd94d956   
259   giw4z3ei           142a615ffb970d12beaa9597bff2b9c49da4bb96   
260   8gfujgxq  428d1091cf63872ea81cb3c1632d76c4813748a1; 8244...   
384   vuzbswvq           9e5c4cfb4582c7aa5e60455ae948554981054c47   
...        ...                                                ...   
4263  htd7dmn9           9a12c1852bf079e75fe2b1bb3186e468081a164e   
4353  da1xab1s           3f1a42a65b20b1ba6e211e411f459cd8ea1af14b   
4711  b5tduubu           6c8ba1999a10405500b412d0b644f0c47d066ec2   
5048  f5mxb040           c04544e941bb99c37c79f23baaf4cf9e64bdb386   
5337  ytq7l5ec           1af946e7a63239d9b462e126f98d0cd6d24df4bd   

                                          Study Type  Clinical-interventional  \
47    ['review', 'meta-analysis', 'pooled analysis']                      0.0   
164   ['review', 'retrospective cohort', 'clinical']                      0.0   
259                      ['review', 'meta-analysis']                      0.0   
260                                       ['review']                      0.0   
384          ['review', 'meta-analysis', 'clinical']                      0.0   
...                                              ...                      ...   
4263                                      ['review']                      0.0   
4353                     ['review', 'meta-analysis']                      0.0   
4711                     ['review', 'meta-analysis']                      0.0   
5048                          ['review', 'clinical']                      0.0   
5337                          ['review', 'clinical']                      0.0   

      Clinical-observational  Systematic review and/or meta-analysis  Other  
47                       0.0                                     2.0    1.0  
164                      0.0                                     2.0    1.0  
259                      0.0                                     2.0    1.0  
260                      0.0                                     2.0    1.0  
384                      0.0                                     2.0    1.0  
...                      ...                                     ...    ...  
4263                     0.0                                     2.0    1.0  
4353                     0.0                                     2.0    1.0  
4711                     0.0                                     2.0    1.0  
5048                     0.0                                     2.0    0.0  
5337                     0.0                                     2.0    1.0  

[63 rows x 7 columns]

In [595]:
pm_merge[pm_merge['Other'] > 1]

Empty DataFrame
Columns: [paper_id, sha, Study Type, Clinical-interventional, Clinical-observational, Systematic review and/or meta-analysis, Other]
Index: []

In [596]:
columns = list(pm_merge.iloc[:,3:])
columns

['Clinical-interventional',
 'Clinical-observational',
 'Systematic review and/or meta-analysis',
 'Other']

In [597]:
count = 0
for i in pm_merge.index:
    for c in columns:
        if (pm_merge[c][count] == 0) | (pm_merge[c][count] == 1.0):
            pass
        elif pm_merge[c][count] > 1.0:
            pm_merge.at[count,c] = 1.0
    count +=1

In [598]:
pm_merge[pm_merge['Clinical-interventional'] > 1]

Empty DataFrame
Columns: [paper_id, sha, Study Type, Clinical-interventional, Clinical-observational, Systematic review and/or meta-analysis, Other]
Index: []

In [599]:
pm_merge[pm_merge['Clinical-observational'] > 1]

Empty DataFrame
Columns: [paper_id, sha, Study Type, Clinical-interventional, Clinical-observational, Systematic review and/or meta-analysis, Other]
Index: []

In [600]:
pm_merge[pm_merge['Systematic review and/or meta-analysis'] > 1]

Empty DataFrame
Columns: [paper_id, sha, Study Type, Clinical-interventional, Clinical-observational, Systematic review and/or meta-analysis, Other]
Index: []

Great! all values >1.0 are made to 1.0

One last check to see how many total labels there are from pm_merge.

In [601]:
total5 = []
for i in range(0,4):
    total5.append(pm_merge.iloc[:,3:].sum()[i])
sum(total5) 

5915.0

Lost about ~250, but still alot of annotations than original 1000.

In [603]:
list(kg_merge)

['paper_id',
 'sha',
 'Study Type',
 'Computational',
 'Experimental - in vitro',
 'Experimental - in vivo',
 'Clinical-interventional',
 'Clinical-observational',
 'Systematic review and/or meta-analysis',
 'Review',
 'Other']

In [605]:
list(pm_merge)

['paper_id',
 'sha',
 'Study Type',
 'Clinical-interventional',
 'Clinical-observational',
 'Systematic review and/or meta-analysis',
 'Other']

In [606]:
#add blank columns to equal kg_merge/cw_merge columns
c = {'Computational': 0, 'Experimental - in vitro': 0, 'Experimental - in vivo': 0, 'Review' : 0}
pm_merge = pm_merge.assign(**c)
pm_merge

paper_id                                       sha  \
0     gi6uaa83  8ae137c8da1607b3a8e4c946c07ca8bda67f88ac   
1     47ema2dq  6a3fa8ed278df0d05c5e009521de11c72308f60b   
2     mtmgur1u  18c21db94a22f1358057c6d797164ffe1585b395   
3     jh9e85c0  d16e1bd4c6cae1bb55dbc695c5e2ba5105a13921   
4     0fitbwuv  d0c6b0c2d387baae89eb2898969913218b3bedff   
...        ...                                       ...   
5742  swafz389  3941c1d823c466b3c789439259c5030ba8f8aaa3   
5743  bupfw5la  e8fb3f9b3a3acda9ebb5cc8ad74624a68c78bbb1   
5744  1k8v0luz  417cc66866cbe8108fbc116d45ec1d5d2ffbe16e   
5745  v6qry3o6  c2d51fee1e73856e4c891437f8349da3eadbe363   
5746  jngto9kv  31105078a2953217223699d09c6a80d0f5edfdf6   

                        Study Type  Clinical-interventional  \
0         ['genetic', 'histories']                      0.0   
1                       ['review']                      0.0   
2                     ['clinical']                      1.0   
3     ['experimental', 'clinical']                      0.0   
4                       ['review']                      0.0   
...                            ...                      ...   
5742                  ['clinical']                      0.0   
5743                  ['clinical']                      0.0   
5744                  ['clinical']                      0.0   
5745                  ['clinical']                      1.0   
5746                    ['review']                      0.0   

      Clinical-observational  Systematic review and/or meta-analysis  Other  \
0                        0.0                                     0.0    1.0   
1                        0.0                                     1.0    1.0   
2                        0.0                                     0.0    0.0   
3                        0.0                                     0.0    1.0   
4                        0.0                                     0.0    1.0   
...                      ...                                     ...    ...   
5742                     0.0                                     0.0    1.0   
5743                     0.0                                     0.0    1.0   
5744                     1.0                                     0.0    0.0   
5745                     0.0                                     0.0    0.0   
5746                     0.0                                     0.0    1.0   

      Computational  Experimental - in vitro  Experimental - in vivo  Review  
0                 0                        0                       0       0  
1                 0                        0                       0       0  
2                 0                        0                       0       0  
3                 0                        0                       0       0  
4                 0                        0                       0       0  
...             ...                      ...                     ...     ...  
5742              0                        0                       0       0  
5743              0                        0                       0       0  
5744              0                        0                       0       0  
5745              0                        0                       0       0  
5746              0                        0                       0       0  

[5747 rows x 11 columns]

In [607]:
#Reorder columns
cols = list(cw_merge)
pm_merge = pm_merge[cols]
pm_merge

paper_id                                       sha  \
0     gi6uaa83  8ae137c8da1607b3a8e4c946c07ca8bda67f88ac   
1     47ema2dq  6a3fa8ed278df0d05c5e009521de11c72308f60b   
2     mtmgur1u  18c21db94a22f1358057c6d797164ffe1585b395   
3     jh9e85c0  d16e1bd4c6cae1bb55dbc695c5e2ba5105a13921   
4     0fitbwuv  d0c6b0c2d387baae89eb2898969913218b3bedff   
...        ...                                       ...   
5742  swafz389  3941c1d823c466b3c789439259c5030ba8f8aaa3   
5743  bupfw5la  e8fb3f9b3a3acda9ebb5cc8ad74624a68c78bbb1   
5744  1k8v0luz  417cc66866cbe8108fbc116d45ec1d5d2ffbe16e   
5745  v6qry3o6  c2d51fee1e73856e4c891437f8349da3eadbe363   
5746  jngto9kv  31105078a2953217223699d09c6a80d0f5edfdf6   

                        Study Type  Computational  Experimental - in vitro  \
0         ['genetic', 'histories']              0                        0   
1                       ['review']              0                        0   
2                     ['clinical']              0                        0   
3     ['experimental', 'clinical']              0                        0   
4                       ['review']              0                        0   
...                            ...            ...                      ...   
5742                  ['clinical']              0                        0   
5743                  ['clinical']              0                        0   
5744                  ['clinical']              0                        0   
5745                  ['clinical']              0                        0   
5746                    ['review']              0                        0   

      Experimental - in vivo  Clinical-interventional  Clinical-observational  \
0                          0                      0.0                     0.0   
1                          0                      0.0                     0.0   
2                          0                      1.0                     0.0   
3                          0                      0.0                     0.0   
4                          0                      0.0                     0.0   
...                      ...                      ...                     ...   
5742                       0                      0.0                     0.0   
5743                       0                      0.0                     0.0   
5744                       0                      0.0                     1.0   
5745                       0                      1.0                     0.0   
5746                       0                      0.0                     0.0   

      Systematic review and/or meta-analysis  Review  Other  
0                                        0.0       0    1.0  
1                                        1.0       0    1.0  
2                                        0.0       0    0.0  
3                                        0.0       0    1.0  
4                                        0.0       0    1.0  
...                                      ...     ...    ...  
5742                                     0.0       0    1.0  
5743                                     0.0       0    1.0  
5744                                     0.0       0    0.0  
5745                                     0.0       0    0.0  
5746                                     0.0       0    1.0  

[5747 rows x 11 columns]

Now merge all three tables and drop duplicates.

In [609]:
kg_merge2 = kg_merge.drop(columns = ['Other']) 
cw_merge2 = cw_merge.drop(columns = ['Other']) 
pm_merge2 = pm_merge.drop(columns = ['Other']) 

In [610]:
pdList = [kg_merge2, cw_merge2, pm_merge2] 
StudyTypeAnnotations2 =  pd.concat(pdList).drop_duplicates()
StudyTypeAnnotations2

paper_id                                       sha  \
0     47ema2dq  6a3fa8ed278df0d05c5e009521de11c72308f60b   
1     9trzqzep  eb4b8f43f68db5e493984b7e4e56d9f804d7e885   
2     hnu8gw6w  2afcf2ab2330cb56ec493f82d87fa0c5b5f076e9   
3     5ulk3euw  9f7ed2037968c63fa97eb6fc7c35e9738a654541   
4     loowpch7  de707f97b534ca340482600ed1f008b20d7b1b8e   
...        ...                                       ...   
5742  swafz389  3941c1d823c466b3c789439259c5030ba8f8aaa3   
5743  bupfw5la  e8fb3f9b3a3acda9ebb5cc8ad74624a68c78bbb1   
5744  1k8v0luz  417cc66866cbe8108fbc116d45ec1d5d2ffbe16e   
5745  v6qry3o6  c2d51fee1e73856e4c891437f8349da3eadbe363   
5746  jngto9kv  31105078a2953217223699d09c6a80d0f5edfdf6   

                                        Study Type  Computational  \
0                                       ['review']            0.0   
1             ['questionnaire', 'cross-sectional']            0.0   
2                      ['time series', 'clinical']            0.0   
3                              ['cross-sectional']            0.0   
4     ['prospective cohort', 'prospective cohort']            0.0   
...                                            ...            ...   
5742                                  ['clinical']            0.0   
5743                                  ['clinical']            0.0   
5744                                  ['clinical']            0.0   
5745                                  ['clinical']            0.0   
5746                                    ['review']            0.0   

      Experimental - in vitro  Experimental - in vivo  \
0                         0.0                     0.0   
1                         0.0                     0.0   
2                         0.0                     0.0   
3                         0.0                     0.0   
4                         0.0                     0.0   
...                       ...                     ...   
5742                      0.0                     0.0   
5743                      0.0                     0.0   
5744                      0.0                     0.0   
5745                      0.0                     0.0   
5746                      0.0                     0.0   

      Clinical-interventional  Clinical-observational  \
0                         0.0                     0.0   
1                         0.0                     1.0   
2                         0.0                     1.0   
3                         0.0                     1.0   
4                         0.0                     1.0   
...                       ...                     ...   
5742                      0.0                     0.0   
5743                      0.0                     0.0   
5744                      0.0                     1.0   
5745                      1.0                     0.0   
5746                      0.0                     0.0   

      Systematic review and/or meta-analysis  Review  
0                                        1.0     0.0  
1                                        0.0     0.0  
2                                        0.0     0.0  
3                                        0.0     0.0  
4                                        0.0     0.0  
...                                      ...     ...  
5742                                     0.0     0.0  
5743                                     0.0     0.0  
5744                                     0.0     0.0  
5745                                     0.0     0.0  
5746                                     0.0     0.0  

[6426 rows x 10 columns]

In [611]:
StudyTypeAnnotations2.to_csv("StudyTypeAnnotations2.csv", index=False)

In [612]:
#kg_merge + cw_merge + pm_merge DFs' rows summation
398+367+5747

6512

Actual label count after all Other columns are dropped.

In [613]:
StudyTypeAnnotations2.iloc[:,3:].sum()

Computational                              60.0
Experimental - in vitro                    61.0
Experimental - in vivo                     52.0
Clinical-interventional                   302.0
Clinical-observational                    761.0
Systematic review and/or meta-analysis    268.0
Review                                     82.0
dtype: float64

In [615]:
total = []
for i in range(0,7):
    total.append(StudyTypeAnnotations2.iloc[:,3:].sum()[i])
sum(total)  #This is after dropping all Other columns!!  

1586.0

In [ ]:
#StudyTypeAnnotations.to_csv("StudyTypeAnnotations.csv", index=False)